### ISSUE TITLE
Trouble getting hello world module to appear

### ISSUE THREAD

**Issue by dsyme** [unipi-itc/IoX#3]
REPRO:
- Compiled and run clean repo. I got an exception because `bin\Debug\Modules` directory didn't exist
- I created that manually, then got another exception. I then realized that compiling `IoX.ModuleExamples.HelloWorld` might be necessary - it's not mentioned in the README.md and not in the main solution.  So I added `IoX.ModuleExamples.HelloWorld`  to the main solution
- However compiling that project failed in the "copy" command.  A file `bin\Debug\Modules\hw` was created, I think by the robocopy, but I think this is meant to be a directory.  So I deleted the file, and added a `mkdir` to created `binaDebug\Modules\hw`
- After that the build completed, but only one file (the DLL) appeared under `bin\Debug\Modules\hw`.  I'm wondering if more should appear (e.g. FSharp.Core.dll and the dll.config)
- In all cases, when I ran the website, the "Modules" and "Manage modules" entries were empty - Hello World was not listed.

**Comment by jschiefer** [comment]
Copying the `iox.conf` file from `IoX.ModuleExamples.HelloWorld\static` into `bin\Debug\Modules\hw` seems to do the trick.

**Comment by cisterni** [comment]
Yup, I've just pushed the fix. In the final refactor I removed a path in the postbuild action that does the robocopy in the Modules dir. Now it works. For the future a cross platform friendly process for this part should be used.
